version: '3'
services:
  redis: # In production, would require a password
    image: redis:latest
    container_name: redis-db
    restart: always
    ports:
      - 6379:6379
  redis-commander:
      image: rediscommander/redis-commander:latest
      container_name: redis-commander
      restart: always
      environment:
      - REDIS_HOSTS=local:redis:6379
      ports:
      - 8081:8081